language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup target add wasm32-unknown-unknown

script:
  - cargo test
  - cd webml-rt && cargo build
  - cd webml-test && cargo test
