fun fib n = case n < 2 of
                true => 1
             |  false =>  fib (n - 1) + fib (n - 2)
val a = printInt (fib 0)
val a = printInt (fib 1)
val a = printInt (fib 2)
val a = printInt (fib 3)
val a = printInt (fib 4)
val a = printInt (fib 5)
